#!/usr/bin/env python

import sys

pkg = 'hector_flexbe_rqt_widget'
widget = 'flexbe_interface_widget'

from rqt_gui.main import Main

main = Main()
sys.exit(main.main(sys.argv, standalone=pkg+'.'+widget))
